package affiliate

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/crypto-casino/core/internal/ledger"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Affiliate commission accrual + payout helpers (E-5).
//
// Two ledger entry types are involved:
//
//   - affiliate.commission: accrual marker. Written as a non-balance event
//     against the partner so the timeline reads "earned $X commission for
//     period Y" even though no cash has moved yet. Pairs with a row in
//     affiliate_commission_grants in 'pending' status.
//   - affiliate.payout: cash credit to the partner's user wallet. Posted at
//     payout time with idempotency key derived from the grant id, then the
//     grant flips to 'paid'.
//
// AccrueDailyCommissions is meant to be called by the worker once per UTC
// day. It looks at NGR generated by referred players in the previous full
// UTC day, multiplies by each partner's revenue_share_bps, and writes the
// pending grant + commission ledger marker. PayPendingGrants is the operator
// payout sweep that converts pending grants into real cash credits.

// AccrueDailyCommissions accrues commission grants for the previous UTC day.
// It is idempotent: re-running for the same period is a no-op because the
// (partner_id, accrual_period, currency) unique constraint on
// affiliate_commission_grants and the deterministic idempotency key on the
// ledger event both block double-write.
//
// "NGR" here is computed as: stake debits − win credits − rollback amounts,
// summed across casino + sportsbook stake/win pockets, on the cash pocket
// only, for users referred by the partner. We don't subtract bonus cost or
// provider fees yet — that's E-6.
func AccrueDailyCommissions(ctx context.Context, pool *pgxpool.Pool) (int, error) {
	if pool == nil {
		return 0, nil
	}
	now := time.Now().UTC()
	dayStart := time.Date(now.Year(), now.Month(), now.Day()-1, 0, 0, 0, 0, time.UTC)
	dayEnd := dayStart.Add(24 * time.Hour)
	period := dayStart.Format("2006-01-02")

	rows, err := pool.Query(ctx, `
		SELECT p.id::text, p.user_id::text,
		       COALESCE(t.ngr_revshare_bps, p.revenue_share_bps, 0)::int
		FROM affiliate_partners p
		LEFT JOIN referral_program_tiers t ON t.id = p.tier_id AND t.active
		WHERE p.status = 'active'
		  AND COALESCE(t.ngr_revshare_bps, p.revenue_share_bps, 0) > 0
	`)
	if err != nil {
		return 0, fmt.Errorf("affiliate: load partners: %w", err)
	}
	defer rows.Close()

	type partner struct {
		id     string
		userID string
		bps    int
	}
	var partners []partner
	for rows.Next() {
		var p partner
		if err := rows.Scan(&p.id, &p.userID, &p.bps); err != nil {
			return 0, fmt.Errorf("affiliate: scan partner: %w", err)
		}
		partners = append(partners, p)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	var accrued int
	for _, p := range partners {
		if err := accrueOnePartner(ctx, pool, p.id, p.userID, p.bps, period, dayStart, dayEnd); err != nil {
			slog.ErrorContext(ctx, "affiliate_accrue_partner_failed", "partner_id", p.id, "err", err)
			continue
		}
		accrued++
	}
	return accrued, nil
}

func accrueOnePartner(ctx context.Context, pool *pgxpool.Pool, partnerID, partnerUserID string, bps int, period string, dayStart, dayEnd time.Time) error {
	// NGR per currency for the partner's referred users in the window.
	// referred_ngr = wager - win - rollback. We bucket by currency so a
	// multi-currency casino can pay commissions in the right unit.
	ngrF := ledger.NGRReportingFilterSQL("le")
	ngrRows, err := pool.Query(ctx, `
		SELECT le.currency,
		       COUNT(DISTINCT le.user_id)::int AS user_count,
		       COALESCE(SUM(CASE WHEN le.entry_type IN ('game.debit','game.bet','sportsbook.debit')
		                         THEN ABS(le.amount_minor) ELSE 0 END),0)::bigint AS wager,
		       COALESCE(SUM(CASE WHEN le.entry_type IN ('game.credit','game.win','game.win_rollback','sportsbook.credit')
		                         THEN le.amount_minor ELSE 0 END),0)::bigint AS win,
		       COALESCE(SUM(CASE WHEN le.entry_type IN ('game.rollback','sportsbook.rollback')
		                         THEN ABS(le.amount_minor) ELSE 0 END),0)::bigint AS rb
		FROM affiliate_referrals ar
		JOIN ledger_entries le ON le.user_id = ar.user_id
		WHERE ar.partner_id = $1::uuid
		  AND le.pocket = 'cash'
		  AND le.entry_type IN ('game.debit','game.bet','game.credit','game.win','game.rollback','game.win_rollback',
		                        'sportsbook.debit','sportsbook.credit','sportsbook.rollback')
		  AND le.created_at >= $2 AND le.created_at < $3 AND `+ngrF+`
		GROUP BY le.currency
	`, partnerID, dayStart, dayEnd)
	if err != nil {
		return fmt.Errorf("ngr query: %w", err)
	}
	defer ngrRows.Close()

	type ngrRow struct {
		currency  string
		userCount int
		wager     int64
		win       int64
		rb        int64
	}
	var ngr []ngrRow
	for ngrRows.Next() {
		var r ngrRow
		if err := ngrRows.Scan(&r.currency, &r.userCount, &r.wager, &r.win, &r.rb); err != nil {
			return err
		}
		ngr = append(ngr, r)
	}
	if err := ngrRows.Err(); err != nil {
		return err
	}

	for _, r := range ngr {
		ngrMinor := r.wager - r.win - r.rb
		if ngrMinor <= 0 {
			continue
		}
		commissionMinor := ngrMinor * int64(bps) / 10_000
		if commissionMinor <= 0 {
			continue
		}

		idem := fmt.Sprintf("affiliate:accrue:%s:%s:%s", partnerID, period, strings.ToUpper(r.currency))

		tx, err := pool.Begin(ctx)
		if err != nil {
			return err
		}
		commit := false
		defer func() {
			if !commit {
				_ = tx.Rollback(ctx)
			}
		}()

		// Insert pending grant. ON CONFLICT (partner_id, accrual_period, currency)
		// DO NOTHING so the worker is idempotent across reruns.
		var grantID string
		err = tx.QueryRow(ctx, `
			INSERT INTO affiliate_commission_grants (
				partner_id, accrual_period, currency, referred_user_count,
				referred_ngr_minor, commission_minor, status, metadata
			)
			VALUES ($1::uuid, $2, $3, $4, $5, $6, 'pending', $7::jsonb)
			ON CONFLICT (partner_id, accrual_period, currency) DO UPDATE
			  SET accrual_period = EXCLUDED.accrual_period
			RETURNING id::text
		`, partnerID, period, strings.ToUpper(r.currency), r.userCount, ngrMinor, commissionMinor,
			mustJSONString(map[string]any{"bps": bps, "wager_minor": r.wager, "win_minor": r.win, "rollback_minor": r.rb})).Scan(&grantID)
		if err != nil {
			return fmt.Errorf("insert grant: %w", err)
		}

		// Non-balance ledger event so the partner's own ledger timeline shows
		// "earned X commission for period Y", even though the cash hasn't
		// moved yet. RecordNonBalanceEvent works inside transactions via the
		// _Tx helper directly.
		_, err = ledger.ApplyCreditWithPocketTx(ctx, tx, partnerUserID, strings.ToUpper(r.currency),
			ledger.EntryTypeAffiliateCommission, idem, 0, ledger.PocketCash, map[string]any{
				"grant_id":         grantID,
				"period":           period,
				"commission_minor": commissionMinor,
				"ngr_minor":        ngrMinor,
				"bps":              bps,
			})
		if err != nil {
			return fmt.Errorf("ledger accrue: %w", err)
		}

		if err := tx.Commit(ctx); err != nil {
			return err
		}
		commit = true
	}
	return nil
}

// PayPendingGrants pays out up to `limit` pending grants by crediting the
// partner's cash pocket and flipping the grant to 'paid'. Idempotency key
// derives from the grant id so retrying after a partial failure still only
// credits once. Returns the number of grants paid.
func PayPendingGrants(ctx context.Context, pool *pgxpool.Pool, limit int) (int, error) {
	if pool == nil || limit <= 0 {
		return 0, nil
	}
	rows, err := pool.Query(ctx, `
		SELECT g.id::text, g.partner_id::text, p.user_id::text, g.currency, g.commission_minor
		FROM affiliate_commission_grants g
		JOIN affiliate_partners p ON p.id = g.partner_id
		WHERE g.status = 'pending' AND g.commission_minor > 0
		  AND p.status = 'active'
		ORDER BY g.created_at ASC
		LIMIT $1
	`, limit)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	type grant struct {
		grantID, partnerID, userID, currency string
		amount                                int64
	}
	var pending []grant
	for rows.Next() {
		var g grant
		if err := rows.Scan(&g.grantID, &g.partnerID, &g.userID, &g.currency, &g.amount); err != nil {
			return 0, err
		}
		pending = append(pending, g)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	var paid int
	for _, g := range pending {
		if err := payOneGrant(ctx, pool, g.grantID, g.userID, g.currency, g.amount); err != nil {
			slog.ErrorContext(ctx, "affiliate_payout_failed", "grant_id", g.grantID, "err", err)
			continue
		}
		paid++
	}
	return paid, nil
}

// PayPendingGrantsForPartnerUser pays pending commission grants for the partner
// profile owned by userID (player "claim" to cash wallet).
func PayPendingGrantsForPartnerUser(ctx context.Context, pool *pgxpool.Pool, userID string, limit int) (int, error) {
	if pool == nil || limit <= 0 || strings.TrimSpace(userID) == "" {
		return 0, nil
	}
	rows, err := pool.Query(ctx, `
		SELECT g.id::text, g.partner_id::text, p.user_id::text, g.currency, g.commission_minor
		FROM affiliate_commission_grants g
		JOIN affiliate_partners p ON p.id = g.partner_id
		WHERE g.status = 'pending' AND g.commission_minor > 0
		  AND p.status = 'active' AND p.user_id = $1::uuid
		ORDER BY g.created_at ASC
		LIMIT $2
	`, userID, limit)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	type grant struct {
		grantID, partnerID, userID, currency string
		amount                                int64
	}
	var pending []grant
	for rows.Next() {
		var g grant
		if err := rows.Scan(&g.grantID, &g.partnerID, &g.userID, &g.currency, &g.amount); err != nil {
			return 0, err
		}
		pending = append(pending, g)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	var paid int
	for _, g := range pending {
		if err := payOneGrant(ctx, pool, g.grantID, g.userID, g.currency, g.amount); err != nil {
			slog.ErrorContext(ctx, "affiliate_payout_user_failed", "grant_id", g.grantID, "err", err)
			continue
		}
		paid++
	}
	return paid, nil
}

func payOneGrant(ctx context.Context, pool *pgxpool.Pool, grantID, userID, currency string, amountMinor int64) error {
	idem := fmt.Sprintf("affiliate:payout:%s", grantID)

	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	commit := false
	defer func() {
		if !commit {
			_ = tx.Rollback(ctx)
		}
	}()

	// Lock grant FOR UPDATE so two payout sweeps cannot race on the same row.
	var status string
	if err := tx.QueryRow(ctx, `
		SELECT status FROM affiliate_commission_grants WHERE id = $1::uuid FOR UPDATE
	`, grantID).Scan(&status); err != nil {
		return err
	}
	if status != "pending" {
		// Another worker already paid or voided it.
		commit = true
		return tx.Commit(ctx)
	}

	if _, err := ledger.ApplyCreditTx(ctx, tx, userID, strings.ToUpper(currency),
		ledger.EntryTypeAffiliatePayout, idem, amountMinor, map[string]any{
			"grant_id": grantID,
		}); err != nil {
		return fmt.Errorf("payout credit: %w", err)
	}

	if _, err := tx.Exec(ctx, `
		UPDATE affiliate_commission_grants
		SET status = 'paid', paid_at = now(), paid_idempotency_key = $2, updated_at = now()
		WHERE id = $1::uuid
	`, grantID, idem); err != nil {
		return err
	}

	if err := tx.Commit(ctx); err != nil {
		return err
	}
	commit = true
	return nil
}

func mustJSONString(v map[string]any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// AttributeReferralPool records a partner_id ↔ user_id link, using the
// partner found via referral_code. Safe to call for users without a code
// (no-op). Called once at registration time after a successful sign-up.
func AttributeReferralPool(ctx context.Context, pool *pgxpool.Pool, userID, code string) error {
	code = NormalizeReferralCode(code)
	if code == "" || pool == nil {
		return nil
	}
	_, err := pool.Exec(ctx, `
		INSERT INTO affiliate_referrals (user_id, partner_id, code)
		SELECT $1::uuid, p.id, p.referral_code
		FROM affiliate_partners p
		WHERE upper(trim(p.referral_code)) = $2 AND p.status = 'active'
		  AND p.user_id IS DISTINCT FROM $1::uuid
		ON CONFLICT (user_id) DO NOTHING
	`, userID, code)
	return err
}

// AttributeReferralTx is the transactional variant of AttributeReferralPool,
// used when registration is happening inside a larger transaction (e.g. the
// sign-up handler creates user+session+attribution in one go).
func AttributeReferralTx(ctx context.Context, tx pgx.Tx, userID, code string) error {
	code = NormalizeReferralCode(code)
	if code == "" || tx == nil {
		return nil
	}
	_, err := tx.Exec(ctx, `
		INSERT INTO affiliate_referrals (user_id, partner_id, code)
		SELECT $1::uuid, p.id, p.referral_code
		FROM affiliate_partners p
		WHERE upper(trim(p.referral_code)) = $2 AND p.status = 'active'
		  AND p.user_id IS DISTINCT FROM $1::uuid
		ON CONFLICT (user_id) DO NOTHING
	`, userID, code)
	return err
}
